### ISSUE TITLE
[Site] Implement Martech scripts

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#26]
Check on original site and with TechDivision colleagues. Currently used:

- [ ] Google Tag Manager
- [ ] UserCentrics

Also found "raven.js" an old Sentry script, this should not be used any more.

**Comment by denkelt** [comment]
As discussed with Philipp:
- raven.js to be removed
- slick.js to be removed
- fonts.gstatic to be removed / ignored

Regarding GTM and UserCentrics we need to go in discussion with the client.
Since we can expect that the html markup will be much different then before,
maybe we need some adjustments to track as properly as before.

**Comment by SusanneKreis** [comment]
Der Code ist der folgende:
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '[https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)](https://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore%28j,f%29);
        })(window,document,'script','dataLayer','GTM-TVJ7Z6');</script>
Außerdem auch usercentrics:
<script id="usercentrics-cmp" data-settings-id="76VFFxyB" src="https://app.usercentrics.eu/browser-ui/latest/bundle.js" defer></script>
